### ISSUE TITLE
1.19.2 compatibility

### ISSUE THREAD

**Issue by KaTulib** [Jaxydog/Cheese#2]
Hi, not sure if im just silly but is this meant to be compatible with 1.19.2? the modrinth page says 1.19-1.19.3 but when i launch fabric says its a 1.19.3 and above mod.
eager to hear back this mod looks fun!

**Comment by Jaxydog** [comment]
Ah, that's my mistake, sorry! I must have set the version numbers on the Modrinth page incorrectly.

The only *technically* supported versions are 1.19.3 and 1.20.1 as those are the versions I've developed the mod with; I'll update the Modrinth page to reflect that, and once I have a bit more time I can look into back-porting to 1.19.x.

Sorry for the confusion!
