### ISSUE TITLE
Not a issue, it's a request

### ISSUE THREAD

**Issue by Titi68730** [Jaxydog/Cheese#3]
Hello dear devs,
I've seen your mod, and I'm very excited to try it. I was just wondering, is there the Raclette cheese and all the stuff in the mod?
If not, I hope you guys can code it and adding it soon. Thanks! :D

**Comment by Jaxydog** [comment]
Currently I don't have specific cheese types, just a general "cheese" which could theoretically be anything.
In the future I may add different types, though! But sorry to disappoint for the time being :(
